### ISSUE TITLE
Latest Reveal.js version has different structure than before

### ISSUE THREAD

**Issue by AbdBarho** [ReDI-School/js-berlin-2020-spring#18]
The latest and newest `Reveal.js@4.0.0` was released yesterday, deployment on unpkg has apparently changed, as all requests are returning a `404`.

How to reproduce:
go to this link and open the console:
https://redi-school.github.io/js-berlin-2020-spring/#/

**Comment by haraldF** [comment]
Thanks @AbdBarho , I've hard-coded the versions back to 3.9.2 for now
